---
- name: install | Install GPFS S3 packages
  yum:
   name: "{{ scale_install_all_packages }}"
   state: present
   disable_gpg_check: "{{ scale_disable_gpgcheck }}"
  when: inventory_hostname in scale_s3_node_list
