---
# defaults file for remote_mount
scale_remotemount_debug: false
scale_remotemount_forceRun: false

# retries - 2 minutes (40 x 3 seconds)
scale_remotemount_restapi_retries_count: 40
scale_remotemount_restapi_retries_delay: 3

scale_remotemount_client_cluster_gui_port: 443
scale_remotemount_storage_cluster_gui_port: 443

scale_remotemount_scalemgmt_endpoint: "scalemgmt/v2"
scale_remotemount_endpoint: "{{ scale_remotemount_scalemgmt_endpoint }}/remotemount"


scale_remotemount_validate_certs_uri: 'no'

scale_cluster_authorization_cleanup: true

# Temporary Storage for Public Key, Only used when debuging
scale_remotemount_client_access_key: /tmp/client_cluster.pub

# Sets the security mode for communications between the current cluster and the remote cluster
# Encyption can have performance effect and increased CPU usage
# mmauth show ciphers
# Supported ciphers for nistCompliance=SP800-131A:
#        AES128-SHA
#        AES128-SHA256
#        AES256-SHA
#        AES256-SHA256

# AES128-SHA', 'AES256-SHA' , AUTHONLY
scale_remotemount_remotecluster_chipers: "AUTHONLY"

# Storage filesystem
# scale_remotemount_access_mount_attributes: "rw"

# Indicates when the file system is to be mounted:
# yes :When the GPFS daemon starts.
# no: Manual mount. This is the default.
# automount : When the file system is first accessed.
## scale_remotemount_client_mount_fs: "yes"

# Controls the order in which the individual file systems are mounted at daemon startup or when one of the all keywords is specified on the mmmount command
# File systems with higher Priority numbers are mounted after file systems with lower numbers. File systems that do not have mount priorities are mounted last. A value of zero indicates no priority.
## scale_remotemount_client_mount_priority: "0"

# If Accessing/Client Cluster dont have GUI, it will use CLI
scale_remotemount_client_no_gui: False

# Client Cluster (Access) is downloding the pubkey from Owning cluster and importing it.
scale_remotemount_storage_pub_key_location: "/tmp/storage_cluster_public_key.pub"
scale_remotemount_storage_pub_key_location_json: "/tmp/storage_cluster_public_key_json.pub"
scale_remotemount_storage_pub_key_delete: true

# Unmounts, remove the filesystem, and also the connection between Accessing/Client cluster and Owner/Storage Cluster.
# This only works if both systems have GUI/RESTAPI interface
scale_remotemount_cleanup_remote_mount: false

# Spectrum Scale uses the Deamon Node Name and the IP Attach to connect and run Cluster traffic. in most cases the admin network and deamon network is the same.
# In case you have different AdminNode address and DeamonNode address and for some reason you want to use admin network, then you can set the variable: scale_remotemount_storage_adminnodename: true
# Default = DeamonNodeName
scale_remotemount_storage_adminnodename: false


# Added check that GPFS deamon is started on GUI node, it will check the first server in NodeClass GUI_MGMT_SERVERS
# Check can be disabled with changing the flag to false.
scale_remotemount_gpfsdemon_check: true

# Default it will try to mount the filesystem on all client cluster (accessing) nodes, here you can replace the this with a comma seperated list of servers.
# scale1-test,scale2-test
# scale_remotemount_client_mount_on_nodes: all

# When we are adding the storage Cluster in client cluster we need to spesify what nodes should be used. and in normal cases all nodes would be fine.
# In cases we have AFM Gateway nodes, or Cloud nodes TFCT, we want to use the RESTAPI filter to remove those nodes so they are not used.
# Example and the default below is to only list all servers that have (AFM) gatewayNode=false.
scale_remotemount_storage_contactnodes_filter: '?fields=roles.gatewayNode%2Cnetwork.daemonNodeName&filter=roles.gatewayNode%3Dfalse'
# Examples:
# NO AFM and CloudGateway: ?fields=roles.gatewayNode%2Cnetwork.daemonNodeName%2Croles.cloudGatewayNode&filter=roles.gatewayNode%3Dfalse%2Croles.cloudGatewayNode%3Dfalse
# to create your own filter, go to the API Explorer on Spectrum Scale GUI. https://IP-TO-GUI-NODE/ibm/api/explorer/#!/Spectrum_Scale_REST_API_v2/nodesGetv2
# Roles in version 5.1.1.3
#      "roles": {
#        "cesNode": false,
#        "cloudGatewayNode": false,
#        "cnfsNode": false,
#        "designation": "quorum",
#        "gatewayNode": false,
#        "managerNode": false,
#        "otherNodeRoles": "perfmonNode",
#        "quorumNode": true,
#        "snmpNode": false
