---
# Cleaning the GKLM Admin password which are stored locally.

# Make default variables available in hostvars

- name: Encryption | Cleaning the GKLM secret files
  file:
    path: "{{ gklm_dir }}/.gklm_pass"
    state: absent
  register: cleanup_output
  run_once: true

- debug:
    var: cleanup_output.json
  when: cleanup_output is defined

- name: Creating password_update_success file on remote server for validation
  lineinfile:
    dest: "{{ gklm_dir }}/password_update_success"
    create: yes
    line: "This file is for validation purpose."
  run_once: true