---

##################### Failover For CES Nodes #####################

- name: Check if the file exists
  command: ls "/var/mmfs/etc/mmcesExtendedIpMgmt"
  register: file_check_result
  ignore_errors: yes
  when: scale_protocol_node | default(false) == true
  failed_when: file_check_result.rc == 1

- name: Print file existence status
  debug:
    msg: "mmcesExtendedIpMgmt file dont exists."
  when: scale_protocol_node | default(false) == true and file_check_result.rc != 0

- name: Copy mmcesExtendedIpMgmt file
  copy:
    src: "{{ failover_script_path }}"
    dest: /var/mmfs/etc/mmcesExtendedIpMgmt
  register: copy_result
  when: scale_protocol_node | default(false) == true and file_check_result.rc != 0

- name: Set execution permissions using shell command
  shell: chmod +x /var/mmfs/etc/mmcesExtendedIpMgmt
  when: scale_protocol_node | default(false) == true and file_check_result.rc != 0

- name: Fetch environmental variable from Ansible controller
  shell: "echo $IC_API_KEY" 
  register: env_var_output
  delegate_to: localhost
  when: scale_protocol_node | default(false) == true

- name: Replace IC_API_KEY with specified lines
  replace:
    path: /var/mmfs/etc/mmcesExtendedIpMgmt
    regexp: 'IC_API_KEY='
    replace: |
      IC_API_KEY={{ env_var_output.stdout }}
  when: "scale_protocol_node | default(false) == true and file_check_result.rc != 0 and 'IC_API_KEY=' is match"