---
- name: Upgrade SSSD packages
  hosts: localhost
  tasks:

    - name: LDAP | Check OS version for OpenLDAP package installation
      ansible.builtin.shell: "grep -oE 'release [0-9]+' /etc/redhat-release | awk '{print $2}'"
      register: rhel_version
      changed_when: false

    - name: Upgrade sssd-tools and python3-sssdconfig to the latest version with --nobest
      ansible.builtin.command:
        cmd: "dnf update -y --nobest sssd-tools python3-sssdconfig"

    - name: LDAP | Install Required OpenLDAP Packages
      ansible.builtin.dnf:
        name:
          - libnsl
          - libnsl2
          - openldap-clients
          - sssd
          - sssd-ldap
          - oddjob-mkhomedir
          - openssl-perl
          - authselect
        state: present
      when: rhel_version.stdout in ['8', '9']
