---
# Installing required LDAP client packages for integration.

- name: LDAP | Check OS version for OpenLDAP package installation
  ansible.builtin.shell: "grep -oE 'release [0-9]+' /etc/redhat-release | awk '{print $2}'"
  register: rhel_version
  changed_when: false

- block:
    - name: Upgrade sssd-tools and python3-sssdconfig to the latest version
      ansible.builtin.command:
        cmd: "dnf update -y sssd-tools python3-sssdconfig --allowerasing"

    - name: LDAP | Install required OpenLDAP packages
      ansible.builtin.dnf:
        name:
          - libnsl
          - libnsl2
          - openldap-clients
          - sssd
          - sssd-ldap
          - oddjob-mkhomedir
          - openssl-perl
          - authselect
        state: present
  when: rhel_version.stdout in ['8', '9']
