---
# Authenticating LDAP to the cluster

- name: LDAP | CES - Check if LDAP authentication is already configured
  shell: mmuserauth service list
  register: ldap_config_check
  changed_when: false
  run_once: true

- name: LDAP | CES - Authenticate Cluster with LDAP
  shell: |
    echo -e "{{ ldap_admin_password }}" | mmuserauth service create \
      --type ldap \
      --data-access-method file \
      --servers {{ ldap_server }} \
      --base-dn "dc={{ BASE_DN.split('.')[0] }},dc={{ BASE_DN.split('.')[1] }}" \
      --user-name "cn=admin,dc={{ BASE_DN.split('.')[0] }},dc={{ BASE_DN.split('.')[1] }}" \
      --netbios-name ces
  when: "'LDAP' not in ldap_config_check.stdout"
  register: ldap_authenticate_cluster
  run_once: true

# Following tasks have been added to prevent updates to the sssd.conf file after "CES - Authenticate Cluster with LDAP."
- name: LDAP | CES - Ensure SSSD Configuration File is Absent
  ansible.builtin.file:
    path: /etc/sssd/sssd.conf
    state: absent
    force: yes
  when: ldap_authenticate_cluster.changed

- name: LDAP | CES - Deploy SSSD Configuration File
  ansible.builtin.template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    mode: '0600'
    owner: root
    group: root
  when: ldap_authenticate_cluster.changed

- name: LDAP | CES - Restart SSSD Service
  ansible.builtin.systemd:
    name: sssd
    state: restarted
    enabled: yes
  when: ldap_authenticate_cluster.changed