---
# Authenticating LDAP to the cluster

- name: LDAP | Check if LDAP is already configured
  shell: mmuserauth service list
  register: ldap_config_check
  changed_when: false
  run_once: true

- name: LDAP | Authenticate Cluster with LDAP
  shell: |
    echo -e "{{ ldap_admin_password }}" | mmuserauth service create \
      --type ldap \
      --data-access-method file \
      --servers {{ ldap_server }} \
      --base-dn "dc={{ BASE_DN.split('.')[0] }},dc={{ BASE_DN.split('.')[1] }}" \
      --user-name "cn=admin,dc={{ BASE_DN.split('.')[0] }},dc={{ BASE_DN.split('.')[1] }}" \
      --netbios-name ces
  when: "'LDAP' not in ldap_config_check.stdout"
  register: ldap_authenticate_cluster
  run_once: true

- name: LDAP | Debug LDAP Authentication Output
  debug:
    var: ldap_authenticate_cluster.stdout_lines
  run_once: true