---
- name: Install GPFS s3 packages
  package:
   name: "{{ scale_install_all_packages }}"
   state: present
  when: scale_install_repository_url is defined and inventory_hostname in scale_s3_node_list


- name: install| Install GPFS S3 deb
  apt:
   deb: "{{ item }}"
   state: present
  when: scale_install_repository_url is not defined and inventory_hostname in scale_s3_node_list
  with_items:
  - "{{ scale_install_all_packages }}"
