---
# Cheking if Auth is already setup if not then Setting up Auth

- name: Check service is already exists
  shell: "/usr/lpp/mmfs/bin/mmuserauth service check | grep -q 'File configuration is USER-DEFINED'"
  register: service_result
  ignore_errors: yes
  failed_when: service_result.rc == 2
  when: is_admin_node | default(false) == true

- name: Service Check Result
  debug:
    var: service_result.rc
  ignore_errors: yes
  when: is_admin_node | default(false) == true

- name: Setup Auth
  shell: "/usr/lpp/mmfs/bin/mmuserauth service create --data-access-method file --type userdefined"
  ignore_errors: yes
  when: is_admin_node | default(false) == true and service_result.rc != 0
  run_once: true