# Creating directory and password file for non-interactive deployment for KeyProtect
# Copy SSL certs from Bootstrap node to Management node

- block:
    - name: KeyProtect Encryption | Encryption Prepare | Check Directory
      stat:
        path: "{{ key_protect_dir }}"
      register: key_protect_dir_stat

    - name: KeyProtect Encryption | Encryption Prepare | Create Directory
      file:
        path: "{{ key_protect_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      when: not key_protect_dir_stat.stat.exists

    - name: KeyProtect Encryption | Encryption Prepare | Password File Check
      stat:
        path: "{{ key_protect_dir }}/{{ kp_resource_prefixs }}.pwd"
      register: password_file_stat

    - name: KeyProtect Encryption | Encryption Prepare | Password File Create
      lineinfile:
        path: "{{ key_protect_dir }}/{{ kp_resource_prefixs }}.pwd"
        line: "{{ scale_encryption_admin_password }}"
        create: yes
      when: not password_file_stat.stat.exists

    - name: KeyProtect Encryption | Encryption Prepare | Port File Check
      stat:
        path: "{{ key_protect_dir }}/{{ kp_resource_prefixs }}.port"
      register: port_file_stat

    - name: KeyProtect Encryption | Encryption Prepare | Port File Create
      lineinfile:
        path: "{{ key_protect_dir }}/{{ kp_resource_prefixs }}.port"
        line: "{{ key_protect_port }}"
        create: yes
      when: not port_file_stat.stat.exists

    - name: KeyProtect Encryption | Encryption Prepare | Copy Certs to Remote Server
      copy:
        src: "{{ item }}"
        dest: "{{ key_protect_dir }}"
        owner: root
        group: root
      with_fileglob:
        - "{{ key_protect_cert_files_dir }}/*"

  when: is_admin_node | default(false) == true and key_protect_dir is defined and key_protect_dir | length > 0
  run_once: true